all_spawn_keys = {
    'ChanceCeiling': {'key': 'ChanceCeiling', 'default': '100', 'multi': 'No'},
    'IgnoreCleanupRules': {'key': 'IgnoreCleanupRules', 'default': 'false', 'multi': 'No'},
    'ReplenishSystems': {'key': 'ReplenishSystems', 'default': 'false', 'multi': 'No'},
    'PauseAutopilotAtPlayerDistance': {'key': 'PauseAutopilotAtPlayerDistance ', 'default': '-1', 'multi': 'No'},
    'ForceStaticGrid': {'key': 'ForceStaticGrid', 'default': 'false', 'multi': 'No'},
    'RotateFirstCockpitToForward': {'key': 'RotateFirstCockpitToForward', 'default': 'true', 'multi': 'No'},
    'SpawnRandomCargo': {'key': 'SpawnRandomCargo', 'default': 'true', 'multi': 'No'},
    'DisableDampeners': {'key': 'DisableDampeners', 'default': 'false', 'multi': 'No'},
    'ReactorsOn': {'key': 'ReactorsOn', 'default': 'true', 'multi': 'No'},
    'RemoveVoxelsIfGridRemoved': {'key': 'RemoveVoxelsIfGridRemoved', 'default': 'true', 'multi': 'No'},
    'InitializeStoreBlocks': {'key': 'InitializeStoreBlocks', 'default': 'false', 'multi': 'No'},
    'ContainerTypesForStoreOrders': {'key': 'ContainerTypesForStoreOrders', 'default': 'none', 'multi': 'No'},
    'UsePlayerCredits': {'key': 'UsePlayerCredits', 'default': 'false', 'multi': 'No'},
    'IncludeAllPlayersInRadius': {'key': 'IncludeAllPlayersInRadius', 'default': 'false', 'multi': 'No'},
    'IncludeFactionBalance': {'key': 'IncludeFactionBalance', 'default': 'false', 'multi': 'No'},
    'PlayerCreditsCheckRadius': {'key': 'PlayerCreditsCheckRadius', 'default': '15000', 'multi': 'No'},
    'MinimumPlayerCredits': {'key': 'MinimumPlayerCredits ', 'default': '-1', 'multi': 'No'},
    'MaximumPlayerCredits': {'key': 'MaximumPlayerCredits ', 'default': '-1', 'multi': 'No'},
    'FactionOwner': {'key': 'FactionOwner', 'default': 'SPRT', 'multi': 'No'},
    'UseRandomMinerFaction': {'key': 'UseRandomMinerFaction', 'default': 'false', 'multi': 'No'},
    'UseRandomBuilderFaction': {'key': 'UseRandomBuilderFaction', 'default': 'false', 'multi': 'No'},
    'UseRandomTraderFaction': {'key': 'UseRandomTraderFaction', 'default': 'false', 'multi': 'No'},
    'UseKnownPlayerLocations': {'key': 'UseKnownPlayerLocations', 'default': 'false', 'multi': 'No'},
    'KnownPlayerLocationMustMatchFaction': {'key': 'KnownPlayerLocationMustMatchFaction', 'default': 'false', 'multi': 'No'},
    'KnownPlayerLocationMinSpawnedEncounters': {'key': 'KnownPlayerLocationMinSpawnedEncounters ', 'default': '-1', 'multi': 'No'},
    'KnownPlayerLocationMaxSpawnedEncounters': {'key': 'KnownPlayerLocationMaxSpawnedEncounters ', 'default': '-1', 'multi': 'No'},
    'RequireAllMods': {'key': 'RequireAllMods', 'default': 'none', 'multi': 'No'},
    'RequireAnyMods': {'key': 'RequireAnyMods', 'default': 'none', 'multi': 'No'},
    'ExcludeAllMods': {'key': 'ExcludeAllMods', 'default': 'none', 'multi': 'No'},
    'ExcludeAnyMods': {'key': 'ExcludeAnyMods', 'default': 'none', 'multi': 'No'},
    'ModBlockExists': {'key': 'ModBlockExists', 'default': 'none', 'multi': 'No'},
    'MinAirDensity': {'key': 'MinAirDensity', 'default': '-1', 'multi': 'No'},
    'MaxAirDensity': {'key': 'MaxAirDensity', 'default': '-1', 'multi': 'No'},
    'MinGravity': {'key': 'MinGravity ', 'default': '-1', 'multi': 'No'},
    'MaxGravity': {'key': 'MaxGravity ', 'default': '-1', 'multi': 'No'},
    'MinSpawnFromPlanetSurface': {'key': 'MinSpawnFromPlanetSurface ', 'default': '-1', 'multi': 'No'},
    'MaxSpawnFromPlanetSurface': {'key': 'MaxSpawnFromPlanetSurface ', 'default': '-1', 'multi': 'No'},
    'MinWaterDepth': {'key': 'MinWaterDepth', 'default': '0', 'multi': 'No'},
    'UseDayOrNightOnly': {'key': 'UseDayOrNightOnly', 'default': 'false', 'multi': 'No'},
    'SpawnOnlyAtNight': {'key': 'SpawnOnlyAtNight', 'default': 'false', 'multi': 'No'},
    'UseWeatherSpawning': {'key': 'UseWeatherSpawning', 'default': 'false', 'multi': 'No'},
    'AllowedWeatherSystems': {'key': 'AllowedWeatherSystems', 'default': 'none', 'multi': 'No'},
    'UseTerrainTypeValidation': {'key': 'UseTerrainTypeValidation', 'default': 'false', 'multi': 'No'},
    'AllowedTerrainTypes': {'key': 'AllowedTerrainTypes', 'default': 'none', 'multi': 'No'},
    'PlanetBlacklist': {'key': 'PlanetBlacklist', 'default': 'none', 'multi': 'No'},
    'PlanetWhitelist': {'key': 'PlanetWhitelist', 'default': 'none', 'multi': 'No'},
    'PlanetRequiresVacuum': {'key': 'PlanetRequiresVacuum', 'default': 'false', 'multi': 'No'},
    'PlanetRequiresAtmo': {'key': 'PlanetRequiresAtmo', 'default': 'false', 'multi': 'No'},
    'PlanetRequiresOxygen': {'key': 'PlanetRequiresOxygen', 'default': 'false', 'multi': 'No'},
    'PlanetMinimumSize': {'key': 'PlanetMinimumSize ', 'default': '-1', 'multi': 'No'},
    'PlanetMaximumSize': {'key': 'PlanetMaximumSize ', 'default': '-1', 'multi': 'No'},
    'UsePlayerCountCheck': {'key': 'UsePlayerCountCheck', 'default': 'false', 'multi': 'No'},
    'PlayerCountCheckRadius': {'key': 'PlayerCountCheckRadius ', 'default': '-1', 'multi': 'No'},
    'MinimumPlayers': {'key': 'MinimumPlayers ', 'default': '-1', 'multi': 'No'},
    'MaximumPlayers': {'key': 'MaximumPlayers ', 'default': '-1', 'multi': 'No'},
    'RequiredPlayersOnline': {'key': 'RequiredPlayersOnline', 'default': 'none', 'multi': 'Yes'},
    'RequiredAnyPlayersOnline': {'key': 'RequiredAnyPlayersOnline', 'default': 'none', 'multi': 'Yes'},
    'UsePlayerFactionReputation': {'key': 'UsePlayerFactionReputation', 'default': 'false', 'multi': 'No'},
    'PlayerReputationCheckRadius': {'key': 'PlayerReputationCheckRadius', 'default': '15000', 'multi': 'No'},
    'CheckReputationAgainstOtherNPCFaction': {'key': 'CheckReputationAgainstOtherNPCFaction', 'default': 'false', 'multi': 'No'},
    'MinimumReputation': {'key': 'MinimumReputation ', 'default': '-1501', 'multi': 'No'},
    'MaximumReputation': {'key': 'MaximumReputation', 'default': '1501', 'multi': 'No'},
    'UniqueEncounter': {'key': 'UniqueEncounter', 'default': 'false', 'multi': 'No'},
    'AdminSpawnOnly': {'key': 'AdminSpawnOnly', 'default': 'false', 'multi': 'No'},
    'UseRemoteControlCodeRestrictions': {'key': 'UseRemoteControlCodeRestrictions', 'default': 'false', 'multi': 'No'},
    'RemoteControlCode': {'key': 'RemoteControlCode', 'default': 'none', 'multi': 'No'},
    'RemoteControlCodeMinDistance': {'key': 'RemoteControlCodeMinDistance ', 'default': '-1', 'multi': 'No'},
    'RemoteControlCodeMaxDistance': {'key': 'RemoteControlCodeMaxDistance ', 'default': '-1', 'multi': 'No'},
    'Territory': {'key': 'Territory', 'default': 'none', 'multi': 'No'},
    'MinDistanceFromTerritoryCenter': {'key': 'MinDistanceFromTerritoryCenter ', 'default': '-1', 'multi': 'No'},
    'MaxDistanceFromTerritoryCenter': {'key': 'MaxDistanceFromTerritoryCenter ', 'default': '-1', 'multi': 'No'},
    'UseThreatLevelCheck': {'key': 'UseThreatLevelCheck', 'default': 'false', 'multi': 'No'},
    'ThreatLevelCheckRange': {'key': 'ThreatLevelCheckRange', 'default': '5000', 'multi': 'No'},
    'ThreatIncludeOtherNpcOwners': {'key': 'ThreatIncludeOtherNpcOwners', 'default': 'false', 'multi': 'No'},
    'ThreatScoreMinimum': {'key': 'ThreatScoreMinimum ', 'default': '-1', 'multi': 'No'},
    'ThreatScoreMaximum': {'key': 'ThreatScoreMaximum ', 'default': '-1', 'multi': 'No'},
    'UsePCUCheck': {'key': 'UsePCUCheck', 'default': 'false', 'multi': 'No'},
    'PCUCheckRadius': {'key': 'PCUCheckRadius', 'default': '5000', 'multi': 'No'},
    'PCUMinimum': {'key': 'PCUMinimum ', 'default': '-1', 'multi': 'No'},
    'PCUMaximum': {'key': 'PCUMaximum ', 'default': '-1', 'multi': 'No'},
    'AttachModStorageComponentToGrid': {'key': 'AttachModStorageComponentToGrid', 'default': 'false', 'multi': 'No'},
    'StorageKey': {'key': 'StorageKey', 'default': 'none', 'multi': 'No'},
    'StorageValue': {'key': 'StorageValue', 'default': 'none', 'multi': 'No'},
    'MinSpawnFromWorldCenter': {'key': 'MinSpawnFromWorldCenter ', 'default': '-1', 'multi': 'No'},
    'MaxSpawnFromWorldCenter': {'key': 'MaxSpawnFromWorldCenter ', 'default': '-1', 'multi': 'No'},
    'ClearAuthorship': {'key': 'ClearAuthorship', 'default': 'false', 'multi': 'No'},
    'Block': {'key': 'Bloc', 'default': '', 'multi': 'Replacement   false   No'},
    'ReplaceBlockOld': {'key': 'ReplaceBlockOld', 'default': '', 'multi': '/A   Yes'},
    'ReplaceBlockNew': {'key': 'ReplaceBlockNew', 'default': '', 'multi': '/A   Yes'},
    'UseBlockReplacerProfile': {'key': 'UseBlockReplacerProfile', 'default': 'false', 'multi': 'No'},
    'BlockReplacerProfileNames': {'key': 'BlockReplacerProfileNames', 'default': 'none', 'multi': 'No'},
    'RelaxReplacedBlocksSize': {'key': 'RelaxReplacedBlocksSize', 'default': 'false', 'multi': 'No'},
    'AlwaysRemoveBlock': {'key': 'AlwaysRemoveBlock', 'default': 'false', 'multi': 'No'},
    'IgnoreGlobalBlockReplacer': {'key': 'IgnoreGlobalBlockReplacer', 'default': 'false', 'multi': 'No'},
    'ConvertToHeavyArmor': {'key': 'ConvertToHeavyArmor', 'default': 'false', 'multi': 'No'},
    'EraseIngameScripts': {'key': 'EraseIngameScripts', 'default': 'false', 'multi': 'No'},
    'DisableTimerBlocks': {'key': 'DisableTimerBlocks', 'default': 'false', 'multi': 'No'},
    'DisableSensorBlocks': {'key': 'DisableSensorBlocks', 'default': 'false', 'multi': 'No'},
    'DisableWarheads': {'key': 'DisableWarheads', 'default': 'false', 'multi': 'No'},
    'DisableThrustOverride': {'key': 'DisableThrustOverride', 'default': 'false', 'multi': 'No'},
    'DisableGyroOverride': {'key': 'DisableGyroOverride', 'default': 'false', 'multi': 'No'},
    'EnableBlocksWithName': {'key': 'EnableBlocksWithName', 'default': 'none', 'multi': 'No'},
    'DisableBlocksWithName': {'key': 'DisableBlocksWithName', 'default': 'none', 'multi': 'No'},
    'AllowPartialNames': {'key': 'AllowPartialNames', 'default': 'false', 'multi': 'No'},
    'ReduceBlockBuildStates': {'key': 'ReduceBlockBuildStates', 'default': 'false', 'multi': 'No'},
    'MinimumBlocksPercent': {'key': 'MinimumBlocksPercent', 'default': '10', 'multi': 'No'},
    'MaximumBlocksPercent': {'key': 'MaximumBlocksPercent', 'default': '40', 'multi': 'No'},
    'MinimumBuildPercent': {'key': 'MinimumBuildPercent', 'default': '10', 'multi': 'No'},
    'MaximumBuildPercent': {'key': 'MaximumBuildPercent', 'default': '75', 'multi': 'No'},
    'OverrideBlockDamageModifier': {'key': 'OverrideBlockDamageModifier', 'default': 'false', 'multi': 'No'},
    'BlockDamageModifier': {'key': 'BlockDamageModifier', 'default': '100', 'multi': 'No'},
    'GridsAreEditable': {'key': 'GridsAreEditable', 'default': 'true', 'multi': 'No'},
    'GridsAreDestructable': {'key': 'GridsAreDestructable', 'default': 'true', 'multi': 'No'},
    'AssignContainerTypesToAllCargo': {'key': 'AssignContainerTypesToAllCargo', 'default': 'none', 'multi': 'No'},
    'UseContainerTypeAssignment': {'key': 'UseContainerTypeAssignment', 'default': 'none', 'multi': 'No'},
    'ContainerTypeAssignBlockName': {'key': 'ContainerTypeAssignBlockName', 'default': 'none', 'multi': 'Yes'},
    'ContainerTypeAssignSubtypeId': {'key': 'ContainerTypeAssignSubtypeId', 'default': 'none', 'multi': 'Yes'},
    'ShiftBlockColorsHue': {'key': 'ShiftBlockColorsHue', 'default': 'false', 'multi': 'No'},
    'RandomHueShift': {'key': 'RandomHueShift', 'default': 'false', 'multi': 'No'},
    'ShiftBlockColorAmount': {'key': 'ShiftBlockColorAmount', 'default': '0', 'multi': 'No'},
    'AssignGridSkin': {'key': 'AssignGridSkin', 'default': 'none', 'multi': 'No'},
    'RecolorGrid': {'key': 'RecolorGrid', 'default': 'false', 'multi': 'No'},
    'RecolorOld': {'key': 'RecolorOld', 'default': 'none', 'multi': 'Yes'},
    'RecolorNew': {'key': 'RecolorNew', 'default': 'none', 'multi': 'Yes'},
    'ReskinTarget': {'key': 'ReskinTarget', 'default': 'none', 'multi': 'Yes'},
    'ReskinTexture': {'key': 'ReskinTexture', 'default': 'none', 'multi': 'Yes'},
    'SkinRandomBlocks': {'key': 'SkinRandomBlocks', 'default': 'false', 'multi': 'No'},
    'SkinRandomBlocksTextures': {'key': 'SkinRandomBlocksTextures', 'default': '', 'multi': '/A Yes'},
    'MinPercentageSkinRandomBlocks': {'key': 'MinPercentageSkinRandomBlocks', 'default': '10', 'multi': 'No'},
    'MaxPercentageSkinRandomBlocks': {'key': 'MaxPercentageSkinRandomBlocks', 'default': '40', 'multi': 'No'},
    'UseRandomNameGenerator': {'key': 'UseRandomNameGenerator', 'default': 'false', 'multi': 'No'},
    'RandomGridNamePrefix': {'key': 'RandomGridNamePrefix', 'default': 'none', 'multi': 'No'},
    'RandomGridNamePattern': {'key': 'RandomGridNamePattern', 'default': 'none', 'multi': 'No'},
    'ReplaceAntennaNameWithRandomizedName': {'key': 'ReplaceAntennaNameWithRandomizedName', 'default': 'none', 'multi': 'No'},
    'UseBlockNameReplacer': {'key': 'UseBlockNameReplacer', 'default': 'none', 'multi': 'No'},
    'ReplaceBlockNameOld': {'key': 'ReplaceBlockNameOld', 'default': 'none', 'multi': 'Yes'},
    'ReplaceBlockNameNew': {'key': 'ReplaceBlockNameNew', 'default': 'none', 'multi': 'Yes'},
    'AddDefenseShieldBlocks': {'key': 'AddDefenseShieldBlocks', 'default': 'false', 'multi': 'No'},
    'IgnoreShieldProviderMod': {'key': 'IgnoreShieldProviderMod', 'default': 'false', 'multi': 'No'},
    'ConfigureSpecialNpcThrusters': {'key': 'ConfigureSpecialNpcThrusters', 'default': 'false', 'multi': 'No'},
    'RestrictNpcIonThrust': {'key': 'RestrictNpcIonThrust', 'default': 'false', 'multi': 'No'},
    'NpcIonThrustForceMultiply': {'key': 'NpcIonThrustForceMultiply', 'default': '1', 'multi': 'No'},
    'NpcIonThrustPowerMultiply': {'key': 'NpcIonThrustPowerMultiply', 'default': '1', 'multi': 'No'},
    'RestrictNpcAtmoThrust': {'key': 'RestrictNpcAtmoThrust', 'default': 'false', 'multi': 'No'},
    'NpcAtmoThrustForceMultiply': {'key': 'NpcAtmoThrustForceMultiply', 'default': '1', 'multi': 'No'},
    'NpcAtmoThrustPowerMultiply': {'key': 'NpcAtmoThrustPowerMultiply', 'default': '1', 'multi': 'No'},
    'RestrictNpcHydroThrust': {'key': 'RestrictNpcHydroThrust', 'default': 'false', 'multi': 'No'},
    'NpcHydroThrustForceMultiply': {'key': 'NpcHydroThrustForceMultiply', 'default': '1', 'multi': 'No'},
    'NpcHydroThrustPowerMultiply': {'key': 'NpcHydroThrustPowerMultiply', 'default': '1', 'multi': 'No'},
    'ChangeTurretSettings': {'key': 'ChangeTurretSettings', 'default': 'false', 'multi': 'No'},
    'TurretRange': {'key': 'TurretRange', 'default': '800', 'multi': 'No'},
    'TurretIdleRotation': {'key': 'TurretIdleRotation', 'default': 'false', 'multi': 'No'},
    'TurretTargetMeteors': {'key': 'TurretTargetMeteors', 'default': 'true', 'multi': 'No'},
    'TurretTargetMissiles': {'key': 'TurretTargetMissiles', 'default': 'true', 'multi': 'No'},
    'TurretTargetCharacters': {'key': 'TurretTargetCharacters', 'default': 'true', 'multi': 'No'},
    'TurretTargetSmallGrids': {'key': 'TurretTargetSmallGrids', 'default': 'true', 'multi': 'No'},
    'TurretTargetLargeGrids': {'key': 'TurretTargetLargeGrids', 'default': 'true', 'multi': 'No'},
    'TurretTargetStations': {'key': 'TurretTargetStations', 'default': 'true', 'multi': 'No'},
    'TurretTargetNeutrals': {'key': 'TurretTargetNeutrals', 'default': 'true', 'multi': 'No'},
    'RandomizeWeapons': {'key': 'RandomizeWeapons', 'default': 'false', 'multi': 'No'},
    'IgnoreWeaponRandomizerMod': {'key': 'IgnoreWeaponRandomizerMod', 'default': 'false', 'multi': 'No'},
    'WeaponRandomizerBlacklist': {'key': 'WeaponRandomizerBlacklist', 'default': 'none', 'multi': 'No'},
    'WeaponRandomizerWhitelist': {'key': 'WeaponRandomizerWhitelist', 'default': 'none', 'multi': 'No'},
    'IgnoreWeaponRandomizerTargetGlobalBlacklist': {'key': 'IgnoreWeaponRandomizerTargetGlobalBlacklist', 'default': 'false', 'multi': 'No'},
    'IgnoreWeaponRandomizerTargetGlobalWhitelist': {'key': 'IgnoreWeaponRandomizerTargetGlobalWhitelist', 'default': 'false', 'multi': 'No'},
    'WeaponRandomizerTargetBlacklist': {'key': 'WeaponRandomizerTargetBlacklist', 'default': 'none', 'multi': 'No'},
    'WeaponRandomizerTargetWhitelist': {'key': 'WeaponRandomizerTargetWhitelist', 'default': 'none', 'multi': 'No'},
    'SpaceCargoShip': {'key': 'SpaceCargoShip', 'default': 'false', 'multi': 'No'},
    'LunarCargoShip': {'key': 'LunarCargoShip', 'default': 'false', 'multi': 'No'},
    'UseAutoPilotInSpace': {'key': 'UseAutoPilotInSpace', 'default': 'false', 'multi': 'No'},
    'SpaceCargoShipChance': {'key': 'SpaceCargoShipChance', 'default': '100', 'multi': 'No'},
    'LunarCargoShipChance': {'key': 'LunarCargoShipChance', 'default': '100', 'multi': 'No'},
    'SpaceRandomEncounter': {'key': 'SpaceRandomEncounter', 'default': 'false', 'multi': 'No'},
    'RandomEncounterChance': {'key': 'RandomEncounterChance', 'default': '100', 'multi': 'No'},
    'AtmosphericCargoShip': {'key': 'AtmosphericCargoShip', 'default': 'false', 'multi': 'No'},
    'GravityCargoShip': {'key': 'GravityCargoShip', 'default': 'false', 'multi': 'No'},
    'AtmosphericCargoShipChance': {'key': 'AtmosphericCargoShipChance', 'default': '100', 'multi': 'No'},
    'GravityCargoShipChance': {'key': 'GravityCargoShipChance', 'default': '100', 'multi': 'No'},
    'SkipAirDensityCheck': {'key': 'SkipAirDensityCheck', 'default': 'false', 'multi': 'No'},
    'PlanetaryInstallation': {'key': 'PlanetaryInstallation', 'default': 'false', 'multi': 'No'},
    'PlanetaryInstallationType': {'key': 'PlanetaryInstallationType', 'default': 'Small', 'multi': 'No'},
    'PlanetaryInstallationChance': {'key': 'PlanetaryInstallationChance', 'default': '100', 'multi': 'No'},
    'RotateInstallations': {'key': 'RotateInstallations', 'default': 'none', 'multi': 'No'},
    'ReverseForwardDirections': {'key': 'ReverseForwardDirections', 'default': 'none', 'multi': 'No'},
    'InstallationTerrainValidation': {'key': 'InstallationTerrainValidation', 'default': 'false', 'multi': 'No'},
    'InstallationSpawnsOnDryLand': {'key': 'InstallationSpawnsOnDryLand', 'default': 'true', 'multi': 'No'},
    'InstallationSpawnsUnderwater': {'key': 'InstallationSpawnsUnderwater', 'default': 'false', 'multi': 'No'},
    'InstallationSpawnsOnWaterSurface': {'key': 'InstallationSpawnsOnWaterSurface', 'default': 'false', 'multi': 'No'},
    'CutVoxelsAtAirtightCells': {'key': 'CutVoxelsAtAirtightCells', 'default': 'false', 'multi': 'No'},
    'BossEncounterSpace': {'key': 'BossEncounterSpace', 'default': 'false', 'multi': 'No'},
    'BossEncounterAtmo': {'key': 'BossEncounterAtmo', 'default': 'false', 'multi': 'No'},
    'BossEncounterAny': {'key': 'BossEncounterAny', 'default': 'false', 'multi': 'No'},
    'BossEncounterChance': {'key': 'BossEncounterChance', 'default': '100', 'multi': 'No'},
    'BossCustomAnnounceEnable': {'key': 'BossCustomAnnounceEnable', 'default': 'none', 'multi': 'No'},
    'BossCustomAnnounceAuthor': {'key': 'BossCustomAnnounceAuthor', 'default': 'none', 'multi': 'No'},
    'BossCustomAnnounceMessage': {'key': 'BossCustomAnnounceMessage', 'default': 'none', 'multi': 'No'},
    'BossCustomGPSLabel': {'key': 'BossCustomGPSLabel', 'default': 'Dangerous', 'multi': 'Encounter No'},
    'RivalAiSpawn': {'key': 'RivalAiSpawn', 'default': 'false', 'multi': 'No'},
    'RivalAiSpaceSpawn': {'key': 'RivalAiSpaceSpawn', 'default': 'false', 'multi': 'No'},
    'RivalAiAtmosphericSpawn': {'key': 'RivalAiAtmosphericSpawn', 'default': 'false', 'multi': 'No'},
    'RivalAiAnySpawn': {'key': 'RivalAiAnySpawn', 'default': 'false', 'multi': 'No'},
    'UseRivalAi': {'key': 'UseRivalAi', 'default': 'false', 'multi': 'No'},
    'RivalAiReplaceRemoteControl': {'key': 'RivalAiReplaceRemoteControl', 'default': 'false', 'multi': 'No'},
    'ApplyBehaviorToNamedBlock': {'key': 'ApplyBehaviorToNamedBlock', 'default': 'none', 'multi': 'No'},
    'ConvertAllRemoteControlBlocks': {'key': 'ConvertAllRemoteControlBlocks', 'default': 'false', 'multi': 'No'},
    'Modular': {'key': 'Modular', 'default': 'Encounters', 'multi': 'Territory  none    No'},
    'Name': {'key': 'Name', 'default': 'none', 'multi': 'No'},
    'Type': {'key': 'Type', 'default': 'none', 'multi': 'No'},
    'Active': {'key': 'Active', 'default': 'true', 'multi': 'No'},
    'Radius': {'key': 'Radius', 'default': '0', 'multi': 'No'},
    'ScaleRadiusWithPlanetSize': {'key': 'ScaleRadiusWithPlanetSize', 'default': 'false', 'multi': 'No'},
    'CoordsX': {'key': 'CoordsX', 'default': '0', 'multi': 'No'},
    'CoordsY': {'key': 'CoordsY', 'default': '0', 'multi': 'No'},
    'CoordsZ': {'key': 'CoordsZ', 'default': '0', 'multi': 'No'},
    'AnnounceArriveDepart': {'key': 'AnnounceArriveDepart', 'default': 'false', 'multi': 'No'},
    'CustomArriveMessage': {'key': 'CustomArriveMessage', 'default': 'none', 'multi': 'No'},
    'CustomDepartMessage': {'key': 'CustomDepartMessage', 'default': 'none', 'multi': 'No'},
    'PlanetGeneratorName': {'key': 'PlanetGeneratorName', 'default': 'none', 'multi': 'No'}
}




'''
  <NpcSpawnGroupBlacklist>
    <string>(NPC-VOID) Stingray1xBaby</string>
    <string>(NPC-VOID) Stingray2xBaby</string>
    <string>(NPC-VOID) Stingray2xBaby1xBro</string>
    <string>(NPC-VOID) 2xStingray</string>
    <string>(NPC-VOID) 2xStingray2xBaby</string>
    <string>(NPC-GIRR) 2xHauler1xTransport</string>
    <string>(NPC-GIRR) 1xHauler2xTransport</string>
    <string>(NPC-GIRR) 1xHauler1xTransport1xMiner</string>
    <string>(NPC-GIRR) 1xHauler1xTransport1xMerchant</string>
    <string>(NPC-GIRR) 1xHauler2xMiner</string>
    <string>(NPC-GIRR) 1xHauler1xMiner1xMerchant</string>
    <string>(NPC-GIRR) 1xTransport1xMiner1xMerchant</string>
    <string>(NPC-GIRR) 1xTransport2xMerchant</string>
    <string>(NPC-PRTH) 1xSpeartip2xNymph</string>
    <string>(NPC-PRTH) 1xHoplon1xSpeartip</string>
    <string>(NPC-PRTH) 1xHoplon1xThunderbolt</string>
    <string>(NPC-VOID) 2xStingray4xBaby</string>
    <string>(NPC-GIRR) 1xHauler1xTransport1xMiner1xMerchant</string>
    <string>(NPC-GIRR) 1xTransport1xMiner2xMerchant</string>
    <string>(NPC-GIRR) 1xHauler3xMiner</string>
    <string>(NPC-GIRR) 1xHauler1xTransport2xMerchant</string>
    <string>(NPC-PRTH) 1xHoplon1xSpeartip1xThunderbolt</string>
    <string>(NPC-PRTH) 1xHoplon1xThunderbolt2xNymph</string>
    <string>(NPC-PRTH) 1xHoplon1xThunderbolt1xSpeartip1xNymph</string>
    <string>(NPC-GIRR) 1xCruiserNospawn</string>
    <string>(NPC-GIRR) 1xCruiser1xMiner1xMerchant</string>
    <string>(NPC-VOID) Sting Daddy</string>
    <string>(NPC-GIRR) 1xCruiserSpawn</string>
  </NpcSpawnGroupBlacklist>

'''
